# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/anipic/ # 프로젝트 이름
    overwrite: yes
    runas: ec2-user

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777
#
#hooks:
#  ApplicationStart:
#    - location: scripts/run_new_was.sh
#      timeout: 180
#
#    - location: scripts/health_check.sh
#      timeout: 180
#
#    - location: scripts/switch.sh
#      timeout: 180
