spring:
  datasource:
    url: jdbc:mysql://rds.crcp79odgpcq.ap-northeast-2.rds.amazonaws.com/snsdb
    username: admin
    password: pizzadbmysql1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true #파일 업로드 가능여부
      location: /Users/upload #업로드된 파일의 임시 저장 경로
      max-request-size: 30MB #한 번에 최대 업로드 가능 용량
      max-file-size: 10MB # 파일 하나의 최대 크기

    multipart2:
      enabled: true
      location: /Users/profileImg
      max-request-size: 30MB
      max-file-size: 10MB

    devtools:       # 등록한 프로필 사진을 바로 보여주는 설정
      livereload:
        enabled: true
      remote:
        restart:
          enabled: true

  security:
    oauth2:
      client:
        registration:
          #Google
          google:
            client-id: 709627835975-csuqklg0dv8onspg1uq4l8vp4lebni6v.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
#        provider:
#          #KAKAO
#          kakao:
#            authorization_uri: https://kauth.kakao.com/oauth/authorize
#            token_uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kauth.kakao.com/oauth/v2/user/me
#            user_name_attribute: id

custom:
  oauth2:
    kakao:
      client-id: a20980458986232608718c57c6d843e9

logging:
  level:
    javawebdev.petsns: debug

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: javawebdev.petsns.*.dto

upload:
  path: '/Users/upload'

  path2: '/Users/profileImg/'
